name: Automerge

on:
  push:
    branches:
      - DEV_MAIN

env:

  MY_REPO: https://vicky-volocopter:${{secrets.GITHUB_TOKEN}}@github.com:vicky-volocopter/TC_REPO.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: DEV_MAIN

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/vicky-volocopter/TC_REPO.git

  # replace "master" with your master branch name
  MASTER_BRANCH: TC_QA

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
